### ISSUE TITLE
must use real path?

### ISSUE THREAD

**Issue by wwb-dev** [dericofilho/php.tools#31] opened 2015-03-04 02:10 UTC
``` shell
[wenbin@dev test]$ pwd
/home/wenbin/tmp/test
[wenbin@dev test]$ ls
test.php
[wenbin@dev test]$ ls ~/workspace/cmd/fmt.phar
/home/wenbin/workspace/cmd/fmt.phar
[wenbin@dev test]$ fmt.phar test.php 
Formatting ...
! 0

 0 files total
Took 0s
Files not found: 
	 - /home/wenbin/workspace/cmd/test.php
[wenbin@dev test]$ fmt.phar `pwd`/test.php 
Formatting ...
.
 1 files total
Took 0s
```

**Comment by dericofilho** [comment] 2015-03-04 06:28
@wwb-dev I am really sorry for this bug. I am going to fix it ASAP.

**Comment by dericofilho** [comment] 2015-03-04 15:56
@wwb-dev I could not reproduce this bug. Are you sure you are running the latest version?

```
$ cat test-undo.php
<?php

if (true) {
echo "test"; // Hello World
}

$ php fmt.phar test-undo.php
Formatting ...
.
 1 files total
Took 0.01s

$ cat test-undo.php
<?php

if (true) {
	echo "test"; // Hello World
}
```

**Comment by dericofilho** [comment] 2015-03-04 15:58
@wwb-dev I might have found the bug. Just to be sure, are you running your fmt.phar from your $PATH, right?

**Comment by dericofilho** [comment] 2015-03-04 16:01
@wwb-dev Please, update to https://github.com/dericofilho/php.tools/commit/88b921c657350fb5c10f6da4995af36b676918e5

**Comment by dericofilho** [comment] 2015-03-04 16:01
@wwb-dev I shall wait for your feedback before closing this issue.

**Comment by wwb-dev** [comment] 2015-03-04 20:08
@dericofilho it's ok now.

**Comment by dericofilho** [comment] 2015-03-04 20:10
@wwb-dev thanks for using the tool.

**Closed by dericofilho** 2015-03-04 20:10 UTC
Labels: bug, waiting feedback
